"""initial schema from models

Revision ID: aa4552000831
Revises: 
Create Date: 2025-11-12 01:19:21.357925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4552000831'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create schema and extensions
    op.execute("CREATE SCHEMA IF NOT EXISTS legislatie")
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acte_legislative',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tip_act', sa.String(length=50), nullable=False),
    sa.Column('nr_act', sa.String(length=50), nullable=True),
    sa.Column('data_act', sa.Date(), nullable=True),
    sa.Column('an_act', sa.Integer(), nullable=True),
    sa.Column('titlu_act', sa.Text(), nullable=False),
    sa.Column('emitent_act', sa.String(length=255), nullable=True),
    sa.Column('mof_nr', sa.String(length=50), nullable=True),
    sa.Column('mof_data', sa.Date(), nullable=True),
    sa.Column('mof_an', sa.Integer(), nullable=True),
    sa.Column('url_legislatie', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True, comment='Parsing confidence score (0.00-1.00)'),
    sa.Column('ai_status', sa.String(length=20), nullable=True, comment='AI processing status: pending, processing, completed, error'),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when AI processing completed'),
    sa.Column('ai_error', sa.Text(), nullable=True, comment='AI processing error message if any'),
    sa.Column('metadate', sa.Text(), nullable=True, comment='AI-generated summary/metadata'),
    sa.Column('export_status', sa.String(length=20), nullable=True, comment='Export status: pending, exported, error'),
    sa.Column('export_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when exported to Issue Monitoring'),
    sa.Column('export_error', sa.Text(), nullable=True, comment='Export error message if any'),
    sa.Column('issue_monitoring_id', sa.Integer(), nullable=True, comment='ID in Issue Monitoring database after export'),
    sa.Column('versiune', sa.Integer(), server_default='1', nullable=False, comment='Version number (incremented on updates)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legislatie'
    )
    op.create_index(op.f('ix_legislatie_acte_legislative_an_act'), 'acte_legislative', ['an_act'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_acte_legislative_mof_an'), 'acte_legislative', ['mof_an'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_acte_legislative_tip_act'), 'acte_legislative', ['tip_act'], unique=False, schema='legislatie')
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('denumire', sa.String(length=256), nullable=False, comment='Issue title/name (max 256 chars)'),
    sa.Column('descriere', sa.Text(), nullable=True, comment='Detailed description of the issue'),
    sa.Column('source', sa.String(length=20), nullable=True, comment="Source: 'ai' (extracted) or 'manual' (user-added)"),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True, comment='AI confidence score (0.00-1.00)'),
    sa.Column('issue_monitoring_id', sa.Integer(), nullable=True, comment='ID in Issue Monitoring database after export'),
    sa.Column('data_creare', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_modificare', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='legislatie'
    )
    op.create_index(op.f('ix_legislatie_issues_data_creare'), 'issues', ['data_creare'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_issues_denumire'), 'issues', ['denumire'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_issues_issue_monitoring_id'), 'issues', ['issue_monitoring_id'], unique=True, schema='legislatie')
    op.create_table('linkuri_legislatie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending_scraping', nullable=False),
    sa.Column('acte_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='legislatie'
    )
    op.create_index(op.f('ix_legislatie_linkuri_legislatie_id'), 'linkuri_legislatie', ['id'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_linkuri_legislatie_url'), 'linkuri_legislatie', ['url'], unique=True, schema='legislatie')
    op.create_table('acte_modificari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('versiune', sa.Integer(), nullable=False),
    sa.Column('data_modificare', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tip_modificare', sa.String(length=50), nullable=False, comment='initial, update_full, update_partial'),
    sa.Column('sursa_modificare', sa.String(length=500), nullable=True),
    sa.Column('modificat_de', sa.String(length=100), nullable=True),
    sa.Column('articole_noi', sa.Integer(), nullable=False),
    sa.Column('articole_modificate', sa.Integer(), nullable=False),
    sa.Column('articole_sterse', sa.Integer(), nullable=False),
    sa.Column('total_articole', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['legislatie.acte_legislative.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='legislatie'
    )
    op.create_index(op.f('ix_legislatie_acte_modificari_act_id'), 'acte_modificari', ['act_id'], unique=False, schema='legislatie')
    op.create_table('anexe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False, comment='Reference to parent legislative act'),
    sa.Column('anexa_nr', sa.String(length=50), nullable=True, comment="Annex number/identifier (e.g., 'Anexa 1', 'Anexa A')"),
    sa.Column('ordine', sa.Integer(), nullable=False, comment='Order/sequence number for sorting'),
    sa.Column('titlu', sa.Text(), nullable=True, comment='Annex title/description'),
    sa.Column('continut', sa.Text(), nullable=False, comment='Annex content (text or structured data)'),
    sa.Column('metadate', sa.Text(), nullable=True, comment='AI-generated summary/explanation'),
    sa.Column('ai_status', sa.String(length=20), nullable=True, comment='AI processing status: pending, processing, completed, error'),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when AI processing completed'),
    sa.Column('ai_error', sa.Text(), nullable=True, comment='AI processing error message if any'),
    sa.Column('issue_monitoring_id', sa.Integer(), nullable=True, comment='ID in Issue Monitoring database after export'),
    sa.Column('data_creare', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_modificare', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['legislatie.acte_legislative.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('act_id', 'ordine', name='unique_anexa_per_act'),
    schema='legislatie'
    )
    op.create_index(op.f('ix_legislatie_anexe_act_id'), 'anexe', ['act_id'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_anexe_issue_monitoring_id'), 'anexe', ['issue_monitoring_id'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_anexe_ordine'), 'anexe', ['ordine'], unique=False, schema='legislatie')
    op.create_table('articole',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('articol_nr', sa.String(length=20), nullable=True),
    sa.Column('articol_label', sa.String(length=50), nullable=True),
    sa.Column('titlu_nr', sa.Integer(), nullable=True),
    sa.Column('titlu_denumire', sa.Text(), nullable=True),
    sa.Column('capitol_nr', sa.Integer(), nullable=True),
    sa.Column('capitol_denumire', sa.Text(), nullable=True),
    sa.Column('sectiune_nr', sa.Integer(), nullable=True),
    sa.Column('sectiune_denumire', sa.Text(), nullable=True),
    sa.Column('subsectiune_nr', sa.Integer(), nullable=True),
    sa.Column('subsectiune_denumire', sa.Text(), nullable=True),
    sa.Column('text_articol', sa.Text(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('explicatie', sa.Text(), nullable=True),
    sa.Column('metadate', sa.Text(), nullable=True, comment='AI-generated summary/explanation (replaces explicatie)'),
    sa.Column('ai_status', sa.String(length=20), nullable=True, comment='AI processing status: pending, processing, completed, error'),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when AI processing completed'),
    sa.Column('ai_error', sa.Text(), nullable=True, comment='AI processing error message if any'),
    sa.Column('issue_monitoring_id', sa.Integer(), nullable=True, comment='ID in Issue Monitoring database after export'),
    sa.Column('ordine', sa.Integer(), nullable=True, comment='Order of article in the act (1, 2, 3...)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['legislatie.acte_legislative.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='legislatie'
    )
    op.create_index('idx_articole_act_nr', 'articole', ['act_id', 'articol_nr'], unique=False, schema='legislatie')
    op.create_index('idx_articole_act_ordine', 'articole', ['act_id', 'ordine'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_articole_act_id'), 'articole', ['act_id'], unique=False, schema='legislatie')
    op.create_table('articole_modificari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modificare_id', sa.Integer(), nullable=False),
    sa.Column('articol_id', sa.Integer(), nullable=True, comment='NULL for deleted articles'),
    sa.Column('articol_nr', sa.String(length=20), nullable=True),
    sa.Column('articol_label', sa.String(length=50), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('tip_schimbare', sa.String(length=20), nullable=False, comment='added, modified, deleted, unchanged'),
    sa.Column('text_vechi', sa.Text(), nullable=True),
    sa.Column('issue_vechi', sa.Text(), nullable=True),
    sa.Column('explicatie_veche', sa.Text(), nullable=True),
    sa.Column('text_nou', sa.Text(), nullable=True),
    sa.Column('necesita_reetichetare', sa.Boolean(), nullable=False),
    sa.Column('reetichetat', sa.Boolean(), nullable=False),
    sa.Column('reetichetat_la', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['articol_id'], ['legislatie.articole.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modificare_id'], ['legislatie.acte_modificari.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='legislatie'
    )
    op.create_index(op.f('ix_legislatie_articole_modificari_articol_id'), 'articole_modificari', ['articol_id'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_articole_modificari_modificare_id'), 'articole_modificari', ['modificare_id'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_articole_modificari_reetichetat'), 'articole_modificari', ['reetichetat'], unique=False, schema='legislatie')
    op.create_index(op.f('ix_legislatie_articole_modificari_tip_schimbare'), 'articole_modificari', ['tip_schimbare'], unique=False, schema='legislatie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislatie_articole_modificari_tip_schimbare'), table_name='articole_modificari', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_articole_modificari_reetichetat'), table_name='articole_modificari', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_articole_modificari_modificare_id'), table_name='articole_modificari', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_articole_modificari_articol_id'), table_name='articole_modificari', schema='legislatie')
    op.drop_table('articole_modificari', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_articole_act_id'), table_name='articole', schema='legislatie')
    op.drop_index('idx_articole_act_ordine', table_name='articole', schema='legislatie')
    op.drop_index('idx_articole_act_nr', table_name='articole', schema='legislatie')
    op.drop_table('articole', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_anexe_ordine'), table_name='anexe', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_anexe_issue_monitoring_id'), table_name='anexe', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_anexe_act_id'), table_name='anexe', schema='legislatie')
    op.drop_table('anexe', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_acte_modificari_act_id'), table_name='acte_modificari', schema='legislatie')
    op.drop_table('acte_modificari', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_linkuri_legislatie_url'), table_name='linkuri_legislatie', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_linkuri_legislatie_id'), table_name='linkuri_legislatie', schema='legislatie')
    op.drop_table('linkuri_legislatie', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_issues_issue_monitoring_id'), table_name='issues', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_issues_denumire'), table_name='issues', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_issues_data_creare'), table_name='issues', schema='legislatie')
    op.drop_table('issues', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_acte_legislative_tip_act'), table_name='acte_legislative', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_acte_legislative_mof_an'), table_name='acte_legislative', schema='legislatie')
    op.drop_index(op.f('ix_legislatie_acte_legislative_an_act'), table_name='acte_legislative', schema='legislatie')
    op.drop_table('acte_legislative', schema='legislatie')
    # ### end Alembic commands ###
